"""add ai_score to purchase_order_items

Revision ID: 03feae293ad2
Revises: 8415e2667751
Create Date: 2026-07-22 15:13:39.478263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03feae293ad2'
down_revision: Union[str, Sequence[str], None] = '8415e2667751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "purchase_order_items",
        sa.Column(
            "ai_score",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="AI Reorder Priority Score (0-100)",
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'ai_score')
    # ### end Alembic commands ###
