"""add production table

Revision ID: 0409a4705a3f
Revises: 7237d3adfb56
Create Date: 2026-07-29 14:09:59.079107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0409a4705a3f'
down_revision: Union[str, Sequence[str], None] = '7237d3adfb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column(
            "selling_price",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'selling_price')
    # ### end Alembic commands ###
