"""add production table

Revision ID: 0409a4705a3f
Revises: 7237d3adfb56
Create Date: 2026-07-29 14:09:59.079107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0409a4705a3f'
down_revision: Union[str, Sequence[str], None] = '7237d3adfb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "recipes",
        sa.Column(
            "selling_price",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    op.create_table(
        "productions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "recipe_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "quantity_produced",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "batch_number",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "expiry_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Integer(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_productions_organization_id",
        "productions",
        ["organization_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'selling_price')
    # ### end Alembic commands ###
