"""add purchase order rejection fields

Revision ID: 27780da666b8
Revises: 37ed58ddeeb1
Create Date: 2026-07-28 21:02:58.946482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27780da666b8'
down_revision: Union[str, Sequence[str], None] = '37ed58ddeeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('rejected_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'users', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'rejection_reason')
    op.drop_column('purchase_orders', 'rejected_at')
    op.drop_column('purchase_orders', 'rejected_by')
    # ### end Alembic commands ###
