"""add purchase order approval fields

Revision ID: 37ed58ddeeb1
Revises: ff008e021208
Create Date: 2026-07-28 20:34:34.371036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ed58ddeeb1'
down_revision: Union[str, Sequence[str], None] = 'ff008e021208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_purchase_orders_approved_by_users",
        "purchase_orders",
        "users",
        ["approved_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_purchase_orders_approved_by_users",
        "purchase_orders",
        type_="foreignkey",
    )
    op.drop_column('purchase_orders', 'approval_notes')
    op.drop_column('purchase_orders', 'approved_at')
    op.drop_column('purchase_orders', 'approved_by')
    # ### end Alembic commands ###
