"""add supplier purchasing fields

Revision ID: 3c0c717f6506
Revises: 54c8ae528303
Create Date: 2026-07-27 19:57:37.360815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0c717f6506'
down_revision: Union[str, Sequence[str], None] = '54c8ae528303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "suppliers",
        sa.Column(
            "lead_time_days",
            sa.Integer(),
            nullable=False,
            server_default="2",
        ),
    )
    op.add_column('suppliers', sa.Column('minimum_order_quantity', sa.Float(), nullable=False, server_default="0"))
    op.add_column('suppliers', sa.Column('order_multiple', sa.Float(), nullable=False, server_default="1"))
    # ### end Alembic commands ###
    op.alter_column("suppliers", "lead_time_days", server_default=None)
    op.alter_column("suppliers", "minimum_order_quantity", server_default=None)
    op.alter_column("suppliers", "order_multiple", server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'order_multiple')
    op.drop_column('suppliers', 'minimum_order_quantity')
    op.drop_column('suppliers', 'lead_time_days')
    # ### end Alembic commands ###
