"""your migration

Revision ID: 460b41dea7c2
Revises: 8126e75f5e6e
Create Date: 2026-08-03 13:21:22.690798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460b41dea7c2'
down_revision: Union[str, Sequence[str], None] = '8126e75f5e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_predictions_organization_id'), 'ai_predictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.add_column('batches', sa.Column('remaining_quantity', sa.Float(), nullable=False))
    op.add_column('batches', sa.Column('purchase_price', sa.Float(), nullable=False))
    op.add_column('batches', sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('batches', 'batch_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_batches_expiry_date'), 'batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_organization_id'), 'batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
    op.add_column('inventory_transactions', sa.Column('purchase_order_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('reference', sa.String(length=100), nullable=True))
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_transactions_organization_id'), 'inventory_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_foreign_key(None, 'inventory_transactions', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_transactions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_transactions', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('lead_time_days', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('preferred_order_quantity', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('minimum_order_quantity', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('is_finished_product', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.add_column('purchase_order_items', sa.Column('received_quantity', sa.Float(), server_default='0', nullable=False))
    op.add_column('purchase_order_items', sa.Column('ai_score', sa.Integer(), nullable=False, comment='AI Reorder Priority Score (0-100)'))
    op.add_column('purchase_orders', sa.Column('po_number', sa.String(length=50), nullable=False))
    op.add_column('purchase_orders', sa.Column('order_date', sa.Date(), nullable=False))
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('received_date', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('sent_date', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('rejected_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'purchase_orders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'purchase_orders', 'users', ['rejected_by'], ['id'])
    op.add_column('recipes', sa.Column('yield_quantity', sa.Float(), nullable=False))
    op.add_column('recipes', sa.Column('yield_unit', sa.String(length=50), nullable=False))
    op.add_column('recipes', sa.Column('selling_price', sa.Float(), nullable=False))
    op.add_column('recipes', sa.Column('finished_product_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_recipes_organization_id'), 'recipes', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'recipes', 'products', ['finished_product_id'], ['id'])
    op.add_column('sale_items', sa.Column('unit_price', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('sale_items', sa.Column('revenue', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('sale_items', sa.Column('cost_of_goods_sold', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('sale_items', sa.Column('gross_profit', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.add_column('sales', sa.Column('cost_of_goods_sold', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('gross_profit', sa.Float(), nullable=False))
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.add_column('suppliers', sa.Column('lead_time_days', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('minimum_order_quantity', sa.Float(), nullable=False))
    op.add_column('suppliers', sa.Column('order_multiple', sa.Float(), nullable=False))
    op.add_column('suppliers', sa.Column('preferred_supplier', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('suppliers', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.add_column('wastage_logs', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_wastage_logs_organization_id'), 'wastage_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wastage_logs_organization_id'), table_name='wastage_logs')
    op.drop_column('wastage_logs', 'notes')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.alter_column('suppliers', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('suppliers', 'preferred_supplier')
    op.drop_column('suppliers', 'order_multiple')
    op.drop_column('suppliers', 'minimum_order_quantity')
    op.drop_column('suppliers', 'lead_time_days')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_column('sales', 'gross_profit')
    op.drop_column('sales', 'cost_of_goods_sold')
    op.drop_column('sale_items', 'gross_profit')
    op.drop_column('sale_items', 'cost_of_goods_sold')
    op.drop_column('sale_items', 'revenue')
    op.drop_column('sale_items', 'unit_price')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_organization_id'), table_name='recipes')
    op.drop_column('recipes', 'finished_product_id')
    op.drop_column('recipes', 'selling_price')
    op.drop_column('recipes', 'yield_unit')
    op.drop_column('recipes', 'yield_quantity')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'rejection_reason')
    op.drop_column('purchase_orders', 'rejected_at')
    op.drop_column('purchase_orders', 'rejected_by')
    op.drop_column('purchase_orders', 'approval_notes')
    op.drop_column('purchase_orders', 'approved_at')
    op.drop_column('purchase_orders', 'approved_by')
    op.drop_column('purchase_orders', 'sent_date')
    op.drop_column('purchase_orders', 'received_date')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('purchase_orders', 'notes')
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_column('purchase_orders', 'order_date')
    op.drop_column('purchase_orders', 'po_number')
    op.drop_column('purchase_order_items', 'ai_score')
    op.drop_column('purchase_order_items', 'received_quantity')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_column('products', 'is_finished_product')
    op.drop_column('products', 'minimum_order_quantity')
    op.drop_column('products', 'preferred_order_quantity')
    op.drop_column('products', 'lead_time_days')
    op.drop_column('products', 'supplier_id')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_organization_id'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('inventory_transactions', 'reference')
    op.drop_column('inventory_transactions', 'created_by')
    op.drop_column('inventory_transactions', 'batch_id')
    op.drop_column('inventory_transactions', 'purchase_order_id')
    op.drop_index(op.f('ix_categories_organization_id'), table_name='categories')
    op.drop_index(op.f('ix_batches_organization_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_expiry_date'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.alter_column('batches', 'batch_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('batches', 'received_at')
    op.drop_column('batches', 'purchase_price')
    op.drop_column('batches', 'remaining_quantity')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_ai_predictions_organization_id'), table_name='ai_predictions')
    # ### end Alembic commands ###
