"""inventory model cleanup

Revision ID: 47d6cb1af479
Revises: 03feae293ad2
Create Date: 2026-07-23 12:41:50.029476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d6cb1af479'
down_revision: Union[str, Sequence[str], None] = '03feae293ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches",
        sa.Column(
            "remaining_quantity",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "batches", 
        sa.Column(
            "purchase_price",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "batches",
        sa.Column(
            "purchase_price",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column('batches', sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inventory_transactions', sa.Column('purchase_order_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_foreign_key(None, 'inventory_transactions', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_transactions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_transactions', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='SET NULL')
    op.alter_column('purchase_order_items', 'ai_score',
               existing_type=sa.INTEGER(),
               comment='AI Reorder Priority Score (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.alter_column('purchase_order_items', 'ai_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='AI Reorder Priority Score (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('inventory_transactions', 'created_by')
    op.drop_column('inventory_transactions', 'batch_id')
    op.drop_column('inventory_transactions', 'purchase_order_id')
    op.drop_column('batches', 'received_at')
    op.drop_column('batches', 'purchase_price')
    op.drop_column('batches', 'remaining_quantity')
    # ### end Alembic commands ###
