"""add financial fields to sale_items

Revision ID: 506bad9388e5
Revises: 722ea635d9c0
Create Date: 2026-07-31 02:45:10.976416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506bad9388e5'
down_revision: Union[str, Sequence[str], None] = '722ea635d9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # Step 1: Add columns with temporary default values
    op.add_column(
        "sale_items",
        sa.Column(
            "unit_price",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "sale_items",
        sa.Column(
            "revenue",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "sale_items",
        sa.Column(
            "cost_of_goods_sold",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "sale_items",
        sa.Column(
            "gross_profit",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    # Step 2: Remove the defaults for future inserts
    op.alter_column("sale_items", "unit_price", server_default=None)
    op.alter_column("sale_items", "revenue", server_default=None)
    op.alter_column("sale_items", "cost_of_goods_sold", server_default=None)
    op.alter_column("sale_items", "gross_profit", server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'gross_profit')
    op.drop_column('sale_items', 'cost_of_goods_sold')
    op.drop_column('sale_items', 'revenue')
    op.drop_column('sale_items', 'unit_price')
    # ### end Alembic commands ###
