"""add sale profit fields

Revision ID: 54c8ae528303
Revises: 47d6cb1af479
Create Date: 2026-07-23 19:24:27.077759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c8ae528303'
down_revision: Union[str, Sequence[str], None] = '47d6cb1af479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sales",
        sa.Column(
            "cost_of_goods_sold",
            sa.Float(),
            nullable=False,
            server_default="0"
        )
    )
    op.add_column(
        "sales",
        sa.Column(
            "gross_profit",
            sa.Float(),
            nullable=False,
            server_default="0"
        )
    )
    # ### end Alembic commands ###
    op.alter_column(
        "sales",
        "cost_of_goods_sold",
        server_default=None,
    )

    op.alter_column(
        "sales",
        "gross_profit",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'gross_profit')
    op.drop_column('sales', 'cost_of_goods_sold')
    # ### end Alembic commands ###
