"""add details to audit logs

Revision ID: 6022e77df2ea
Revises: a58b634cdcb0
Create Date: 2026-08-01 21:13:49.664636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6022e77df2ea'
down_revision: Union[str, Sequence[str], None] = 'a58b634cdcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###
