"""add ai reorder fields

Revision ID: 6f6c921cfabd
Revises: ab6f4fc3ba78
Create Date: 2026-07-21 20:40:15.783455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6c921cfabd'
down_revision: Union[str, Sequence[str], None] = 'ab6f4fc3ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "lead_time_days",
            sa.Integer(),
            nullable=False,
            server_default="3",
        ),
    )

    op.add_column(
        "products",
        sa.Column(
            "preferred_order_quantity",
            sa.Float(),
            nullable=False,
            server_default="0",
       ),
    )

    op.add_column(
        "products",
        sa.Column(
            "minimum_order_quantity",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'minimum_order_quantity')
    op.drop_column('products', 'preferred_order_quantity')
    op.drop_column('products', 'lead_time_days')
    # ### end Alembic commands ###
