"""add is_finished_product to products

Revision ID: 722ea635d9c0
Revises: b7c031e11f71
Create Date: 2026-07-30 11:11:46.805835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722ea635d9c0'
down_revision: Union[str, Sequence[str], None] = 'b7c031e11f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "products",
        sa.Column(
            "is_finished_product",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )

    op.alter_column(
        "products",
        "is_finished_product",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_finished_product')
    # ### end Alembic commands ###
