"""recipe yield

Revision ID: 7237d3adfb56
Revises: e55052ef423e
Create Date: 2026-07-29 12:55:07.296295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7237d3adfb56'
down_revision: Union[str, Sequence[str], None] = 'e55052ef423e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "recipes",
        sa.Column(
            "yield_quantity",
            sa.Float(),
            nullable=False,
            server_default="1",
        ),
    )

    op.add_column(
        "recipes",
        sa.Column(
            "yield_unit",
            sa.String(length=50),
            nullable=False,
            server_default="serving",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'yield_unit')
    op.drop_column('recipes', 'yield_quantity')
    # ### end Alembic commands ###
