"""extend purchase orders

Revision ID: 8415e2667751
Revises: f8360366d7ea
Create Date: 2026-07-22 13:27:01.619039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8415e2667751'
down_revision: Union[str, Sequence[str], None] = 'f8360366d7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('po_number', sa.String(length=50), nullable=False))
    op.add_column('purchase_orders', sa.Column('order_date', sa.Date(), nullable=False))
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_foreign_key(None, 'purchase_orders', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('purchase_orders', 'notes')
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_column('purchase_orders', 'order_date')
    op.drop_column('purchase_orders', 'po_number')
    # ### end Alembic commands ###
