"""add notes to wastage logs

Revision ID: b7c031e11f71
Revises: 2bd9cfca35cb
Create Date: 2026-07-29 20:16:50.618242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c031e11f71'
down_revision: Union[str, Sequence[str], None] = '2bd9cfca35cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productions_organization_id'), table_name='productions')
    op.alter_column('recipes', 'finished_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('wastage_logs', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wastage_logs', 'notes')
    op.alter_column('recipes', 'finished_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_productions_organization_id'), 'productions', ['organization_id'], unique=False)
    # ### end Alembic commands ###
