"""add preferred supplier

Revision ID: d322ce2f9616
Revises: 3c0c717f6506
Create Date: 2026-07-28 14:46:06.578762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd322ce2f9616'
down_revision: Union[str, Sequence[str], None] = '3c0c717f6506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "suppliers",
        sa.Column(
            "preferred_supplier",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )

    op.alter_column(
        "suppliers",
        "preferred_supplier",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'preferred_supplier')
    # ### end Alembic commands ###
