"""add received quantity to purchase order item

Revision ID: f7202686b3ce
Revises: d322ce2f9616
Create Date: 2026-07-28 15:22:16.217586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7202686b3ce'
down_revision: Union[str, Sequence[str], None] = 'd322ce2f9616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "purchase_order_items",
        sa.Column(
            "received_quantity",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column(
        "purchase_order_items",
        "received_quantity",
        server_default=None,
    )
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'received_quantity')
    # ### end Alembic commands ###
