"""add supplier_id to products

Revision ID: f8360366d7ea
Revises: 6f6c921cfabd
Create Date: 2026-07-22 12:44:36.746797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8360366d7ea'
down_revision: Union[str, Sequence[str], None] = '6f6c921cfabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_column('products', 'supplier_id')
    # ### end Alembic commands ###
