"""add sent and received dates to purchase orders

Revision ID: ff008e021208
Revises: f7202686b3ce
Create Date: 2026-07-28 19:04:18.179729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff008e021208'
down_revision: Union[str, Sequence[str], None] = 'f7202686b3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('received_date', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('sent_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'sent_date')
    op.drop_column('purchase_orders', 'received_date')
    # ### end Alembic commands ###
